### PR TITLE
Allow Python 3.9 & switch to Poetry

### PR DESCRIPTION
**Pull request by malyvsen**
I need this for `road-segmentation` if I don't want to remove `karlovic`-related functionality or use an old Python.
I tested manually with Python 3.9 and instructions in the readme, seemed to work fine :)

### CODE REVIEW

**Comment by malyvsen** [comment]
If we want to continue using `karlovic` (I have no idea about this tbh), maybe we should consider moving it to Poetry? I can do that :)

**Comment by malyvsen** [comment]
So for this to work with `road-segmentation` we'd also need to publish this change as a new version to pypi

**Review by fippli — DISMISSED** [review]

**Comment by fippli** [comment]
I'll ask @Jim-Holmstroem to also take a look at this

**Comment by samedii** [comment]
@malyvsen note that pytorch doesn't support 3.9 yet so road-segmentation should probably not support it either yet?

**Comment by fippli** [comment]
I'll remove myself as a reviewer and let @samedii @FelixAbrahamsson and @Jim-Holmstroem call the shots.

**Review by samedii — APPROVED** [review]

**Comment by Jim-Holmstroem** [comment]
I think carlovic is going to be around, but probably going to get a big refresh, but that refresh won't make a difference for moving to poetry :)
great work @malyvsen !

**Pull request merged**
